---
title: "Models"
author: "Maxwel C. Oliveira"
date: "October 26, 2016"
output: word_document
---
```{r setup, eacho=False, include = FALSE}
library(drc)
library(ggplot2)
library(stats)

library(mgcv)
library(broom)
library(GGally)
library(gridExtra)
library(AICcmodavg)
library(rpart)
```


```{r loadData, echo=FALSE, warning=FALSE, include=FALSE}
Data=read.csv("dmtotal.csv")
str(Data)
names(Data)
Data$weed=as.factor(Data$weed)
```



```{r Cousens model, echo=FALSE}
ggplot(Data, aes(x=densityweed, y=yl)) + 
  geom_point(aes(color = weed), size=5) + coord_cartesian(ylim = c(-10, 100), xlim=c(0,4)) + labs(y="Biomass Reduction (%)", x="Weed Density", color="Weed") + 
  scale_color_manual(labels = c("Commelina benghalensis", "Richardia brasiliensis"), values = c(1,2)) + theme(axis.text=element_text(size=25, color="black"),
        axis.title=element_text(size=30,face="bold"),
        panel.background = element_rect(colour = "black"),
        strip.background=element_rect(color = "red"), 
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white"), legend.position=c(0.8,0.1), legend.text = element_text(size = 17, colour = "black", angle = 0), legend.title = element_text(face = "bold", size=20), legend.background = element_rect(colour = "black")) +
  geom_smooth(aes(group=weed), method="nls", data=Data, formula=y ~ (I[weed]*x)/(1+(I[weed]/A)*x), method.args=list(start=(I=c(30), A=70)), se=F, linetype=1, alpha=.5, color=c(1,2), size=1)
```


```{r models, echo=FALSE, warning=FALSE}
Cousens.model.1 = nls(yl ~ (I[weed]*densityweed)/(1+(I[weed]/A[weed])*densityweed), alg="port", data=Data, start=list(I=c(60,30), A=c(80,60)), trace=T)

summary(Cousens.model.1, correlation=T)
RMSE(Cousens.model.1, which = NULL)
AIC(Cousens.model.1)
```


```{r reduced model 1, echo=FALSE, warning=FALSE}
Cousens.model.2 = nls(yl ~ (I*densityweed)/(1+(I/A)*densityweed), data=Data, alg="port", start=list(I=40, A=80),  trace=T)

summary(Cousens.model.2, correlation=T)
AIC(Cousens.model.2)
RMSE(Cousens.model.2, which = NULL)
```

```{r testing hypothesis 1, echo=FALSE, warning=FALSE}
anova(Cousens.model.2,Cousens.model.1)
```

```{r reduced model 2, echo=FALSE, warning=FALSE}
Cousens.model.3 = nls(yl ~ (I*densityweed)/(1+(I/A[weed])*densityweed), data=Data, alg="port", start=list(I=60, A=c(80,60)),  trace=T)

summary(Cousens.model.3, correlation=T)
AIC(Cousens.model.3)
RMSE(Cousens.model.3, which = NULL)
```

```{r testing hypothesis 2, echo=FALSE, warning=FALSE}
anova(Cousens.model.3,Cousens.model.1)
```

```{r reduced model 3, echo=FALSE, warning=FALSE}
Cousens.model.4 = nls(yl ~ (I[weed]*densityweed)/(1+(I[weed]/A)*densityweed), data=Data, alg="port",start=list(I=c(30,30), A=70), trace=T)

summary(Cousens.model.4)
AIC(Cousens.model.4)
RMSE(Cousens.model.4, which = NULL)
```

```{r testing hypothesis 3, echo=FALSE, warning=FALSE}
anova(Cousens.model.4,Cousens.model.1)
```


```{r AIC comparison, echo=FALSE, warning=FALSE}
AIC(Cousens.model.1, Cousens.model.2, Cousens.model.3, Cousens.model.4)
```


```{r adding lines plots, echo=FALSE, warning=FALSE}
x=seq(0,4,0.25)
weed1=(159.896*x)/(1+(159.896/109.732)*x)
weed2=(56.432*x)/(1+(56.432/109.732)*x)

lines(x,predict(weed1), lty=1, lwd=5, col=1)
lines(x,predict(Cousens.model.4), lty=c(1,3), lwd=5, col=c(1,2))
```



```{r polynomial quadratic, echo=FALSE}
ggplot(Data, aes(x=densityweed, y=yl)) + 
  geom_point(aes(color = weed), size=5) + coord_cartesian(ylim = c(-10, 100), xlim=c(0,4)) + labs(y="Biomass Reduction (%)", x="Weed Density", color="Weed") + 
  scale_color_manual(labels = c("Commelina benghalensis", "Richardia brasiliensis"), values = c(1,2)) + theme(axis.text=element_text(size=25, color="black"),
        axis.title=element_text(size=30,face="bold"),
        panel.background = element_rect(colour = "black"),
        strip.background=element_rect(color = "red"), 
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white"), legend.position=c(0.8,0.1), legend.text = element_text(size = 17, colour = "black", angle = 0), legend.title = element_text(face = "bold", size=20),
    legend.background = element_rect(colour = "black")) +
  geom_smooth(aes(group=weed), method="lm", data=Data, formula=yl ~ (I[weed]*densityweed)/(1+(I[weed]/A)*densityweed), method.args=list(start=c(I=30,30), A=70))
```

```{r drc, echo=FALSE}

drc.model=drm(yl~densityweed, weed, fct=l4 (fixed =c(NA,NA,NA,NA)),data=Data)
Pred=predict(object=drc.model)


x11()
ggplot(Data, aes(x=densityweed, y=yl)) + 
  geom_point(aes(color = weed), size=5) + coord_cartesian(ylim = c(-10, 100), xlim=c(0,4)) + labs(y="Biomass Reduction (%)", x="Weed Density", color="Weed") + 
  scale_color_manual(labels = c("Commelina benghalensis", "Richardia brasiliensis"), values = c(1,2)) + theme(axis.text=element_text(size=25, color="black"),
        axis.title=element_text(size=30,face="bold"),
        panel.background = element_rect(colour = "black"),
        strip.background=element_rect(color = "red"), 
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_blank(),
        panel.background = element_rect(fill="white"), legend.position=c(0.8,0.1), legend.text = element_text(size = 17, colour = "black", angle = 0), legend.title = element_text(face = "bold", size=20),
    legend.background = element_rect(colour = "black")) +
geom_smooth(aes(group=weed), method="drm", data=Data, formula=l4, se=F, linetype=1, alpha=.5, color=c(1,2), size=1)






```
