---
title: "ggpot figures"
author: "Maxwel C. Oliveira"
date: "July 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(broom)
library(drc)
library(AICcmodavg)
```



```{r}
DMT=read.csv("dmshoot.csv")
head(DMT)
DMT$yl=as.numeric(DMT$yl)
DMT$weed=as.factor(DMT$weed)
str(DMT)
```


```{r}
DMT$weed<-factor(DMT$weed, levels=c("1", "2"), labels=c("Commelina benghalensis", "Richardia brasiliensis"))
```



```{r Full model}
Cousens.model.1 = nls(yl ~ (I[weed]*densityweed)/(1+(I[weed]/A[weed])*densityweed), alg="port", data=DMT, start=list(I=c(60,30), A=c(80,60)), trace=T)

summary(Cousens.model.1, correlation=T)



nd1 = data.frame(densityweed=seq(0, 4, 0.01), weed="Commelina benghalensis")
nd2 = data.frame(densityweed=seq(0, 4, 0.01), weed="Richardia brasiliensis")
nd = rbind(nd1, nd2)

pred<- augment(Cousens.model.1, newdata=nd)
```

```{r}
mse <- mean(residuals(Cousens.model.1)^2/df.residual(Cousens.model.1))
rmse <- sqrt(mse)
rmse
```




```{r Full model}
ggplot(DMT, aes(x=densityweed, y=yl, shape=weed, linetype=weed)) + geom_point(size=3) + geom_line(data = pred, size=1.3, aes(x=densityweed, linetype=weed, y=.fitted)) +
  labs(fill="", y="Yield loss (%)", x=expression(bold(paste("Weed density (plants pot"^"-1",")")))) +
  scale_shape_manual(values = c(1,16)) +
  scale_linetype_manual(values=c(1,2)) +
  scale_y_continuous(limits=c(-25,110), breaks = c(-25,0,25,50,75,100)) +
    theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
  linetype="solid"), legend.position=c(0.7,0.15), legend.text = element_text(size = 16, colour = "black", face="italic"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  +  ggsave("Full.tiff", units="in", width=6, height=6, dpi=800)
```



```{r DRC}
Model=drm(yl~densityweed, weed, fct=l4(), data=DMT)
summary(Model)
AIC(Model)


newdata=expand.grid(densityweed=exp(seq(log(0.05), log(4), length=100)))

nd1 <- data.frame(weed="Commelina benghalensis", newdata)
nd2 <- data.frame(weed="Richardia brasiliensis", newdata)
nd = rbind(nd1, nd2)

pm<- predict(Model, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
```

```{r}
mse <- mean(residuals(Model)^2/df.residual(Model))
rmse <- sqrt(mse)
rmse
```


```{r}
ggplot(DMT, aes(x = densityweed, y = yl, shape=weed, linetype=weed)) +  geom_point(size=3) +
geom_line(data=nd, aes(x=densityweed, y=p, linetype=weed), size=1.3) + 
  labs(fill="", y="Yield loss (%)", x=expression(bold(paste("Weed density (plants pot"^"-1",")")))) +
  scale_shape_manual(values = c(1,16)) +
  scale_linetype_manual(values=c(1,2)) +
  scale_y_continuous(limits=c(-25,110), breaks = c(-25,0,25,50,75,100)) +
    theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
  linetype="solid"), legend.position=c(0.7,0.15), legend.text = element_text(size = 16, colour = "black", face="italic"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  +  
  ggsave("Logistic.tiff", units="in", width=6, height=6, dpi=800)
```




```{r Polynomial}
DMT.m1<- lm(yl ~ densityweed + I(densityweed^2), subset=weed=="Commelina benghalensis", data=DMT)
summary(DMT.m1)

DMT.m2<- lm(yl ~ densityweed + I(densityweed^2), subset=weed=="Richardia brasiliensis", data=DMT)
summary(DMT.m2)


nd1 = data.frame(densityweed=seq(0, 4, 0.01), weed="Commelina benghalensis")
nd2 = data.frame(densityweed=seq(0, 4, 0.01), weed="Richardia brasiliensis")
nd = rbind(nd1, nd2)

pred1<- augment(DMT.m1, newdata=nd)
pred2<- augment(DMT.m2, newdata=nd)

pred<-rbind(pred1, pred2)

AIC=AICc(DMT.m1)+AICc(DMT.m2)
```


```{r}
mse <- mean(residuals(DMT.m2)^2/df.residual(DMT.m2))
rmse <- sqrt(mse)
rmse
```

```{r}
(2.91+3.68)/2
```



```{r polynomial model}
ggplot(DMT, aes(x=densityweed, y=yl, shape=weed, linetype=weed)) + geom_point(size=3) + geom_line(data = pred1, size=1.3, aes(x=densityweed, y=.fitted)) + 
  geom_line(data = pred2, size=1.3, aes(x=densityweed, y=.fitted), linetype=2) +
  labs(fill="", y="Yield loss (%)", x=expression(bold(paste("Weed density (plants pot"^"-2",")")))) +
  scale_shape_manual(values = c(1,16)) +
  scale_linetype_manual(values=c(1,2)) +
  scale_y_continuous(limits=c(-25,110), breaks = c(-25,0,25,50,75,100)) +
    theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
  linetype="solid"), legend.position=c(0.7,0.15), legend.text = element_text(size = 16, colour = "black", face="italic"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  +  ggsave("Polynomial.tiff", units="in", width=6, height=6, dpi=800)
```




```{r Red model}
Cousens.model.4 = nls(yl ~ (I[weed]*densityweed)/(1+(I[weed]/A)*densityweed), data=DMT,  
                      start=list(I=c(30,30), A=70), trace=T) 
summary(Cousens.model.4)



nd1 = data.frame(densityweed=seq(0, 4, 0.01), weed="Commelina benghalensis")
nd2 = data.frame(densityweed=seq(0, 4, 0.01), weed="Richardia brasiliensis")
nd = rbind(nd1, nd2)

pred<- predict(Cousens.model.4, newdata=nd)
```


```{r Red model}
ggplot(DMT, aes(x=densityweed, y=yl, shape=weed, linetype=weed)) + geom_point(size=3) + geom_line(data = nd, size=1.3, aes(x=densityweed, y=pred)) + 
  labs(fill="", y="Yield loss (%)", x=expression(bold(paste("Weed density (plants pot"^"-2",")")))) +
  scale_shape_manual(values = c(1,16)) +
  scale_linetype_manual(values= c(1,2)) +
  scale_y_continuous(limits=c(-25,110), breaks = c(-25,0,25,50,75,100)) +
    theme(axis.text=element_text(size=18, color="black"), 
        axis.title=element_text(size=20,face="bold"), 
        panel.background = element_rect(fill="white", color = "white"), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border = element_rect(fill=NA,color="black", size=0.5, 
  linetype="solid"), legend.position=c(0.7,0.15), legend.text = element_text(size = 16, colour = "black", face="italic"), legend.key = element_rect(fill=NA), legend.key.height  = unit(1.5, "line"), legend.key.width = unit(2.2, "line"),
legend.background = element_rect(fill =NA),  legend.title=element_blank())  +  ggsave("Red.tiff", units="in", width=4, height=4, dpi=800)
```



```{r}
library(AICcmodavg)
```

```{r}
AIC(Cousens.model.1, Cousens.model.4, DMT.m1, DMT.m2)

164.1544+173.5872
```




```{r}
cand.mods<- list(Cousens.model.1,
             Model, DMT.m1, DMT.m2, Cousens.model.4)
Modnames<- c('Full',
             'Logistic','Poly1','Poly2','Red')

aictab(cand.set = cand.mods, modnames = Modnames, sort = TRUE)



citation("AICcmodavg")
```

